### Basic information
site_name: The Marginal Effects Zoo

### Repo information
repo_url: $ALTDOC_PACKAGE_URL_GITHUB
repo_name: $ALTDOC_PACKAGE_NAME

### Plugins
plugins:
  - search

### Theme
theme:
  name: 'material'
  logo: images/marginaleffects_icon.png
  favicon: images/favicon.ico
  features:
    - navigation.footer
  palette: 

  # Palette toggle for light mode
  - scheme: default
    primary: white
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    primary: grey
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

  icon:
    repo: fontawesome/brands/github 
    text: ""

### Remove MkDocs footer
extra:
  generator: false

extra_css:
  - stylesheets/extra.css


### Code highlighting
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


### Navigation tree
nav:
  - Get Started: vignettes/get_started/
  - Tutorials:
      Predictions: vignettes/predictions/
      Comparisons: vignettes/comparisons/
      Slopes: vignettes/slopes/
      Hypothesis Tests: vignettes/hypothesis/
      Plots: vignettes/plot/
  - Case Studies:
      Bayes: vignettes/brms/
      Bootstrap and Simulation: vignettes/bootstrap/
      Categorical outcomes: vignettes/categorical/
      Conformal prediction: vignettes/conformal/
      Elasticity: vignettes/elasticity/
      Equivalence Tests: vignettes/equivalence/
      Experiments: vignettes/experiments/
      GAM: vignettes/gam/
      G-Computation: vignettes/gcomputation/
      Heterogeneity: vignettes/heterogeneity/
      IPW: vignettes/ipw/
      Mixed Effects: vignettes/lme4/
      Logit: vignettes/logit/
      Machine Learning: vignettes/machine_learning/
      Marginal Means: vignettes/marginalmeans/
      Matching: vignettes/matching/
      MrP: vignettes/mrp/
      Missing Data: vignettes/multiple_imputation/
      S Values: vignettes/svalues/
  - Technical Notes:
      Alternative Software: vignettes/alternative_software/
      Extensions: vignettes/extensions/
      Links: vignettes/links/
      Performance: vignettes/performance/
      Python: vignettes/python/
      Supported Models: vignettes/supported_models/
      Tables: vignettes/tables/
      Standard Errors: vignettes/uncertainty/
      FAQ: vignettes/faq/
  - Functions:
      Predictions:
        predictions: man/predictions/
        avg_predictions: man/predictions/
        plot_predictions: man/plot_predictions/
      Comparisons:
        comparisons: man/comparisons/
        avg_comparisons: man/comparisons/
        plot_comparisons: man/plot_comparisons/
      Slopes:
        slopes: man/slopes/
        avg_slopes: man/slopes/
        plot_slopes: man/plot_slopes/
      Grids:
        datagrid: man/datagrid/
        datagridcf: man/datagrid/
      More:
        hypotheses: man/hypotheses/
        inferences: man/inferences/
        marginal_means: man/marginal_means/
        posterior_draws: man/posterior_draws/
        print: man/print.marginaleffects/
  - News: $ALTDOC_NEWS/
  - Changelog: $ALTDOC_CHANGELOG/
  - Code of Conduct: $ALTDOC_CODE_OF_CONDUCT/
  - License: $ALTDOC_LICENSE/
  - Licence: $ALTDOC_LICENCE/
  - Citation: $ALTDOC_CITATION/
